language: java
jdk:
  - openjdk11

os: 
  - linux
  
dist:
  - debian
  
addons:
    sonarcloud:
        organization: "jacopofabi"
        token: "756ceaccf04fdf74fa76877889c6dded08e92f49"
        
script: 
    # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  #- mvn clean verify sonar:sonar -Pcoverage -X
    # JaCoCo is used to have code coverage, the agent has to be activated
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report install sonar:sonar -Pcoverage -PnoTest -X
  - mvn clean verify sonar:sonar -PnoTest